#!/usr/bin/env bash

git push origin --delete gh-pages
git branch -D gh-pages
git checkout -b gh-pages
mv resources/public/* ./
git add .
git commit -m "publishing public"
git push origin gh-pages
git checkout master
